api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api.user.views import ItUserViewSet


router = routers.DefaultRouter()
router.register(r'user', ItUserViewSet)


urlpatterns = [
    url(r'^', include(router.urls)),
]

apps/projects/urls.py
from django.conf.urls import url
from .views import ListEventView, DetailEventView, CreateEventView


urlpatterns = [
    url(r'^$', ListEventView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', DetailEventView.as_view(), name='detail'),
    url(r'^create$', CreateEventView.as_view(), name='create'),
]

base/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from settings import dev as settings

urlpatterns = [
    # contrib
    url(r'^admin/', admin.site.urls),

    # apps
    url(r'^user/', include('apps.users.urls', namespace='user')),
    url(r'^events/', include('apps.events.urls', namespace='event')),
    url(r'^projects/', include('apps.projects.urls', namespace='projects')),

    # rest-api
    url(r'^rest-api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # main
    url(r'^', include('apps.main.urls', namespace='main')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/projects/models.py
from django.db import models
from stdimage.models import StdImageField
from stdimage.validators import MaxSizeValidator
from stdimage.utils import pre_delete_delete_callback, pre_save_delete_callback
from django.db.models.signals import post_delete, pre_save
from settings import default_avatars
from django.utils.translation import ugettext_lazy as _
from utils.choices import CITIES, PROJECT_TYPE
from apps.users.models import Specialty
from apps.users.models import ItUser


def avatar_path(instance, filename):
    return 'avatars/{0}/{1}/{2}/{3}/{4}'.format(instance.city, instance.type,
                                                instance.title[:1], instance.title[:2], instance.title)


class Event(models.Model):
    title = models.CharField(_('Название'), max_length=100)
    # slug = AutoSlugField(populate_from='title', unique_with='date_start__month')
    type = models.CharField(_('Вид проекта'), max_length=100, choices=PROJECT_TYPE, default='hak')
    img = StdImageField(
        _("Аватар"),
        upload_to=avatar_path,
        variations={'thumb': (150, 150, True), 'small': (50, 50, True)},
        validators=[MaxSizeValidator(1028, 768)],
        null=True
    )
    city = models.CharField(_('Город'), max_length=100, choices=CITIES, default='msk')
    specialty = models.ManyToManyField(Specialty, verbose_name=_('Проекту нужны'), related_name='proj_specs')
    about = models.TextField(_('Описание'), max_length=2000)
    facebook = models.CharField(max_length=100, blank=True)
    instagram = models.CharField(max_length=100, blank=True)
    twitter = models.CharField(max_length=100, blank=True)
    vk = models.CharField(max_length=100, blank=True)
    create_by = models.ForeignKey(ItUser, verbose_name=_('Создатель'), related_name='my_projects')
    members = models.ManyToManyField(ItUser, verbose_name=_('Участники'), blank=True, related_name='projects')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Projects'
        verbose_name_plural = 'Projects'

    def get_small_img_url(self):
        try:
            return self.img.small.url
        except AttributeError:
            return default_avatars.DEFAULT_EVENT_AVATAR_SMALL

    def get_thumb_img_url(self):
        try:
            return self.img.thumb.url
        except AttributeError:
            return default_avatars.DEFAULT_EVENT_AVATAR_THUMB


post_delete.connect(pre_delete_delete_callback, sender=Event)
pre_save.connect(pre_save_delete_callback, sender=Event)

apps/projects/forms.py
from django.forms import ModelForm
from django import forms
from .models import Event
from django.contrib.admin import widgets


class EventCreationForm(ModelForm):

    class Meta:
        model = Event
        fields = (
            "title",
            "type",
            "img",
            "specialty",
            "city",
            "about",
            "facebook",
            "instagram",
            "twitter",
            "vk",
        )

    # def __init__(self, *args, **kwargs):
    #     super(EventCreationForm, self).__init__(*args, **kwargs)
    #     self.fields['date_start'].widget = widgets.AdminSplitDateTime()
    #     self.fields['date_end'].widget =

apps/projects/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse
from .models import Event
from .forms import EventCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin


class ListEventView(LoginRequiredMixin, ListView):
    model = Event

    def get_context_data(self, **kwargs):
        context = super(ListEventView, self).get_context_data(**kwargs)
        # context['now'] = timezone.now()
        return context


class DetailEventView(LoginRequiredMixin, DetailView):
    model = Event

    def get_context_data(self, **kwargs):
        context = super(DetailEventView, self).get_context_data(**kwargs)
        # context['now'] = timezone.now()
        return context


class CreateEventView(CreateView):
    template_name = 'projects/create.html'
    form_class = EventCreationForm

    def get_success_url(self):
        return reverse('projects:detail', args=(self.object.pk,))

    def form_valid(self, form):
        form.instance.create_by = self.request.user
        return super(CreateEventView, self).form_valid(form)

templates/projects/create.html
{% extends 'base.html' %}
{% block title %}
    Новое мероприятие
{% endblock %}
{% block content %}
    <div class="right">
<form action="{% url 'projects:create' %}"
      method="post"
      enctype="multipart/form-data"
      class="pure-form pure-form-stacked"
>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="form-control btn-primary" value="Создать проект">
    </form>
    </div>
{% endblock %}

templates/projects/event_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="right">
			<div class="left_container">

				<div class="module_photo shadow_box">
					<div class="cont_event" style="background: url({{ event.img.thumb.url }}) center center / cover no-repeat;">
						<img src="{{ event.img.thumb.url }}" alt="Фотография">
					</div>
					<div class="linev">

						<a class="subscribe" href="#" title="Вступить">Вступить</a>

					</div>
				</div>

				<div class="module_сolleag shadow_box">
					<a class="colleagues" href="#" title="Коллеги">Уже в проекте <strong>(13)</strong></a>
					<div class="mod_colleag_list">
						<a href="#" class="mod_colleag_block">
							<div class="img_colleag" style="background: url(/static/images/nophoto.jpg) center center / cover no-repeat;">
								<img src="/static/images/nophoto.jpg" alt="Не фото">
							</div>
							<div class="txt_colleag">
								<div class="name_colleag">Аида Расулова</div>
								<div class="pos_colleag">Дизайнер</div>
							</div>
						</a>
						<a href="#" class="mod_colleag_block">
							<div class="img_colleag" style="background: url(/static/images/nophoto.jpg) center center / cover no-repeat;">
								<img src="/static/images/nophoto.jpg" alt="Не фото">
							</div>
							<div class="txt_colleag">
								<div class="name_colleag">Магомед Курбанов</div>
								<div class="pos_colleag">androind-разаработчик</div>
							</div>
						</a>
						<a href="#" class="mod_colleag_block">
							<div class="img_colleag" style="background: url(/static/images/nophoto.jpg) center center / cover no-repeat;">
								<img src="/static/images/nophoto.jpg" alt="Не фото">
							</div>
							<div class="txt_colleag">
								<div class="name_colleag">Расул Ахмедов</div>
								<div class="pos_colleag">php-программист</div>
							</div>
						</a>
						<a href="#" class="mod_colleag_block">
							<div class="img_colleag" style="background: url(/static/images/nophoto.jpg) center center / cover no-repeat;">
								<img src="/static/images/nophoto.jpg" alt="Не фото">
							</div>
							<div class="txt_colleag">
								<div class="name_colleag">Магоменд-Расул Гаджимурадов</div>
								<div class="pos_colleag">androind-разаработчик</div>
							</div>
						</a>
					</div>
				</div>

				<div class="module_сolleag shadow_box">
					<a class="colleagues" href="#" title="Коллеги">Онлайн <strong>(3)</strong></a>
					<div class="mod_colleag_list">
						<a href="#" class="mod_colleag_block">
							<div class="img_colleag" style="background: url(/static/images/nophoto.jpg) center center / cover no-repeat;">
								<img src="/static/images/nophoto.jpg" alt="Не фото">
							</div>
							<div class="txt_colleag">
								<div class="name_colleag">Аида Расулова</div>
								<div class="pos_colleag">Дизайнер</div>
							</div>
						</a>
						<a href="#" class="mod_colleag_block">
							<div class="img_colleag" style="background: url(/static/images/nophoto.jpg) center center / cover no-repeat;">
								<img src="/static/images/nophoto.jpg" alt="Не фото">
							</div>
							<div class="txt_colleag">
								<div class="name_colleag">Магомед Курбанов</div>
								<div class="pos_colleag">androind-разаработчик</div>
							</div>
						</a>
						<a href="#" class="mod_colleag_block">
							<div class="img_colleag" style="background: url(/static/images/nophoto.jpg) center center / cover no-repeat;">
								<img src="/static/images/nophoto.jpg" alt="Не фото">
							</div>
							<div class="txt_colleag">
								<div class="name_colleag">Расул Ахмедов</div>
								<div class="pos_colleag">php-программист</div>
							</div>
						</a>
						<a href="#" class="mod_colleag_block">
							<div class="img_colleag" style="background: url(/static/images/nophoto.jpg) center center / cover no-repeat;">
								<img src="/static/images/nophoto.jpg" alt="Не фото">
							</div>
							<div class="txt_colleag">
								<div class="name_colleag">Магоменд-Расул Гаджимурадов</div>
								<div class="pos_colleag">androind-разаработчик</div>
							</div>
						</a>
					</div>
				</div>

			</div>
			<div class="right_container">
			<div class="profile_info shadow_box">
				<div class="block1 evblock1">
					<div class="lefthead_event">
						<div class="title_event">{{ event.title }}</div>
						<div class="type_event">{{ event.get_type_display }}</div>
					</div>
					<div class="righthead_event">
						<img src="/static/images/nophoto.jpg" alt="Нет фото">
						<div class="creat_event">Создатель</div>
						<div class="creator_event">{{ event.create_by.first_name }} {{ event.create_by.second_name }}</div>
					</div>
				</div>
				<div class="block2">
					<div class="row">
						<div class="cell">Город:</div>
						<div class="cell">{{ event.get_city_display }}</div>
					</div>
					<div class="row">
						<div class="cell">Проекту нужны:</div>
						<div class="cell">{% for spec in event.specialty.all %} {{ spec }} {% endfor %}</div>
					</div>
					<div class="row">
						<div class="cell">Описание:</div>
						<div class="cell">{{ event.about }}</div>
					</div>
				</div>
			</div>
			<div class="profile_skills">
				<a href="#" class="skill_teg shadow_box">Python</a>
				<a href="#" class="skill_teg shadow_box">JavaScript</a>
				<a href="#" class="skill_teg shadow_box">Angular</a>
				<a href="#" class="skill_teg shadow_box">Django</a>
				<a href="#" class="skill_teg shadow_box">Redis</a>
				<a href="#" class="skill_teg shadow_box">RestApi</a>
				<a href="#" class="skill_teg shadow_box">Php</a>
				<a href="#" class="skill_teg shadow_box">HTML</a>
				<a href="#" class="skill_teg shadow_box">CSS</a>
				<a href="#" class="skill_teg shadow_box">CSS3</a>
			</div>

			<div class="chat_project shadow_box">

				<div class="chat_title">Чат</div>

				<div class="message_list">
					<div class="message_block">
						<div class="message_img">
							<img src="/static/images/nophoto.jpg" alt="Не фото">
						</div>
						<div class="message_txt">
							<div class="message_name">Аида Расулова</div>
							<div class="message_text">Привет, как дела?</div>
						</div>
					</div>
					<div class="message_block">
						<div class="message_img">
							<img src="/static/images/nophoto.jpg" alt="Не фото">
						</div>
						<div class="message_txt">
							<div class="message_name">Иван Иванов</div>
							<div class="message_text">Привет, хорошо</div>
						</div>
					</div>
					<div class="message_block">
						<div class="message_img">
							<img src="/static/images/nophoto.jpg" alt="Не фото">
						</div>
						<div class="message_txt">
							<div class="message_name">Аида Расулова</div>
							<div class="message_text">Какие у тебя качества?</div>
						</div>
					</div>
					<div class="message_block">
						<div class="message_img">
							<img src="/static/images/nophoto.jpg" alt="Не фото">
						</div>
						<div class="message_txt">
							<div class="message_name">Иван Иванов</div>
							<div class="message_text">Целеустремленность‚ ответственность‚ креативность‚ аккуратность‚ стремление к профессиональному развитию и обучению</div>
						</div>
					</div>
					<div class="message_block">
						<div class="message_img">
							<img src="/static/images/nophoto.jpg" alt="Не фото">
						</div>
						<div class="message_txt">
							<div class="message_name">Аида Расулова</div>
							<div class="message_text">Отлично</div>
						</div>
					</div>
				</div>

				<form class="message_form">
					<textarea type="text" name="" value=""></textarea>
					<input type="submit" value="Отправить">
				</form>
				<div class="rasp"></div>
			</div>

			</div>
		</div>

{% endblock %}

templates/projects/event_list.html
{% extends 'base.html' %}

{% block content %}
<div class="right">
			<div class="headline">
				<div class="head_title">Проекты</div>
				<ul class="head_menu projects_menu">
					<li><a class="active" href="#" title="Разработчики">Разработчики</a></li>
					<li><a href="#" title="Компании">Компании</a></li>
					<li><a href="#" title="Мои проекты">Мои проекты</a></li>
					<li><a href="#" title="Участвую">Участвую</a></li>
				</ul>
				<a class="add_project" href="{% url 'projects:create' %}" title="Добавить проект">Добавить</a>
				<div class="filter">
					<form>
						<input class="input_text search" type="text" value="">
						<select class="input_select">
							<option>Вид проекта</option>
							<option>Open Source</option>
							<option>Социальные</option>
							<option>Коммерческие</option>
						</select>
						<select class="input_select">
							<option>Город</option>
							<option>Москва</option>
							<option>Санкт-питербур</option>
							<option>Махачкала</option>
							<option>Каспийск</option>
							<option>Дербент</option>
							<option>Кизляр</option>
							<option>Хасавюрт</option>
						</select>
						<input class="input_text" type="text" placeholder="Навыки">
					</form>
				</div>
				<div class="filter_but"></div>
			</div>
			<div class="list_item project_list">
                {% for event in event_list %}
				<div class="item_block shadow_box">
				<a class="a_item_block" href="{% url 'projects:detail' event.id %}" title="Название проекта">
					<div class="img_item_project" style="background: url({{ event.img.thumb.url }}) center center / cover no-repeat">
						<img src="{{ event.img.thumb.url }}" alt="Название проекта" style="opacity: 0;">
					</div>
					<div class="title_item">{{ event.title }}</div>
					<div class="desc_item">Проекиу нужны: {% for spec in event.specialty.all %} {{ spec }} {% endfor %}</div>
					<div class="skills_item">
						<a href="#" class="skill_teg_item">Python</a>
						<a href="#" class="skill_teg_item">JavaScript</a>
						<a href="#" class="skill_teg_item">Angular</a>
						<a href="#" class="skill_teg_item">Django</a>
						<a href="#" class="skill_teg_item">Redis</a>
					</div>
				</a>
				</div>
                {% endfor %}

			</div>
		</div>




{% endblock %}