api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api.user.views import ItUserViewSet


router = routers.DefaultRouter()
router.register(r'user', ItUserViewSet)


urlpatterns = [
    url(r'^', include(router.urls)),
]

apps/users/urls.py
from django.conf.urls import url
from .views import LoginView, LogoutView, CreateItUserView, ItUserListView, ItUserDetailView


urlpatterns = [
    url(r'^$', ItUserListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', ItUserDetailView.as_view(), name='detail'),
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^logout$', LogoutView.as_view(), name='logout'),
    url(r'^registration$', CreateItUserView.as_view(), name='registration'),
    # url(r'^update$', UpdateItUserView.as_view(), name='update'),
]

base/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from settings import dev as settings

urlpatterns = [
    # contrib
    url(r'^admin/', admin.site.urls),

    # apps
    url(r'^user/', include('apps.users.urls', namespace='user')),
    url(r'^events/', include('apps.events.urls', namespace='event')),
    url(r'^projects/', include('apps.projects.urls', namespace='projects')),

    # rest-api
    url(r'^rest-api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # main
    url(r'^', include('apps.main.urls', namespace='main')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Главная{% endblock %} | IT Place</title>
  <link rel="stylesheet" href="{% static 'css/forms-min.css' %}">

   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="{% static 'css/reset.css' %}" rel="stylesheet" media="screen">
   <link href="{% static 'css/lightslider.min.css' %}" rel="stylesheet" media="screen">
   <link href="{% static 'css/styles.css' %}" rel="stylesheet" media="screen">
   <link href="{% static 'css/adaptive.css' %}" rel="stylesheet" media="screen">
 </head>
 <body>
	<div class="main_container">
		<header>
			<div class="adaptive">
			<a class="logo" href="/" title="На главную">IT-place</a>
			<ul>
				<li><a href="#" >О проекте</a></li>
				<li><a href="#" >Помощь</a></li>
				<li><a href="{% url 'user:logout' %}" >Выйти</a></li>
			</ul>
			</div>
		</header>
		<section class="adaptive">
		<div class="left">
			<ul class="left_menu shadow_box">
				<li><a href="/" title="Мой профиль">Мой профиль</a></li>
				<li><a href="{% url 'projects:list' %}" title="Проекты">Проекты</a></li>
				<li><a href="{% url 'event:list' %}" title="Мероприятия">Мероприятия</a></li>
				<li><a href="{% url 'user:list' %}" title="Разработчики">Разработчики</a></li>
				<li><a href="#" title="Компании">Компании</a></li>
				<li><a href="#" title="Скринкасты">Скринкасты</a></li>
				<li><a href="#" title="Статьи">Статьи</a></li>
				<li><a href="#" title="Обучение">Обучение</a></li>
			</ul>
		</div>

    {% block content %}

    {% endblock %}

        </section>
	</div>
	<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
	<script src="{% static 'js/lightslider.min.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>
 </body>
</html>