api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api.user.views import ItUserViewSet


router = routers.DefaultRouter()
router.register(r'user', ItUserViewSet)


urlpatterns = [
    url(r'^', include(router.urls)),
]

apps/users/urls.py
from django.conf.urls import url
from .views import LoginView, LogoutView, CreateItUserView, ItUserListView, ItUserDetailView


urlpatterns = [
    url(r'^$', ItUserListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', ItUserDetailView.as_view(), name='detail'),
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^logout$', LogoutView.as_view(), name='logout'),
    url(r'^registration$', CreateItUserView.as_view(), name='registration'),
    # url(r'^update$', UpdateItUserView.as_view(), name='update'),
]

base/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from settings import dev as settings

urlpatterns = [
    # contrib
    url(r'^admin/', admin.site.urls),

    # apps
    url(r'^user/', include('apps.users.urls', namespace='user')),
    url(r'^events/', include('apps.events.urls', namespace='event')),
    url(r'^projects/', include('apps.projects.urls', namespace='projects')),

    # rest-api
    url(r'^rest-api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # main
    url(r'^', include('apps.main.urls', namespace='main')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from stdimage.models import StdImageField
from stdimage.validators import MaxSizeValidator
from stdimage.utils import pre_delete_delete_callback, pre_save_delete_callback
from django.db.models.signals import post_delete, pre_save
from settings import default_avatars
from django.utils.translation import ugettext_lazy as _
from utils.choices import CITIES, SPECIALITIES
from datetime import datetime, date
from django.utils import timezone


def avatar_path(instance, filename):
    return 'avatars/{0}/{1}/{2}/{3}'.format(instance.city, instance.specialty, instance.username[:1],
                                            instance.username[:2], instance.username)


class Specialty(models.Model):
    title = models.CharField(_('Специальность'), max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Specialty'
        verbose_name_plural = 'Specialties'


class ItUser(AbstractUser):

    # signed = models.ForeignKey('ItUser', null=True, blank=True)
    # colleagues = models.ForeignKey('ItUser', null=True, blank=True)
    username = models.CharField(
        _('Логин'),
        max_length=150,
        unique=True,
        validators=[AbstractUser.username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_('Имя'), max_length=30)
    last_name = models.CharField(_('Фамилия'), max_length=30)
    specialty = models.CharField(_('Специальность'), choices=SPECIALITIES, max_length=100)
    birth = models.DateField(_('Дата рождения'), default=timezone.now)
    email = models.EmailField(_('Email'), unique=True)
    img = StdImageField(
        _("Аватар"),
        upload_to=avatar_path,
        variations={'thumb': (150, 150, True), 'small': (50, 50, True)},
        validators=[MaxSizeValidator(1028, 768)],
        null=True
    )
    city = models.CharField(_('Город'), max_length=100, choices=CITIES, default='msk')
    experience = models.CharField(_('Опыт работы'), max_length=100)
    education = models.CharField(_('Образование'), max_length=100)
    about = models.TextField(_('О себе'), max_length=2000)
    skills = models.CharField(
        _('Навыки'),
        max_length=1000,
        help_text=_('например: Python, Photoshop, CSS, Angular - разделять навыки запятыми')
    )
    edu = models.BooleanField(_('Готов обучать'), default=False)
    edu_list = models.CharField(
        _('Могу обучить'),
        max_length=1000,
        help_text=_('например: Python, Photoshop, CSS, Angular'),
        null=True,
        blank=True
    )
    github = models.CharField(max_length=100, blank=True)
    bitbacket = models.CharField("bitbucket", max_length=100, blank=True)
    pinterest = models.CharField(max_length=100, blank=True)
    facebook = models.CharField(max_length=100, blank=True)
    instagram = models.CharField(max_length=100, blank=True)
    twitter = models.CharField(max_length=100, blank=True)
    vk = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'ItUser'
        verbose_name_plural = 'ItUsers'

    def get_small_img_url(self):
        try:
            return self.img.small.url
        except AttributeError:
            return default_avatars.DEFAULT_USER_AVATAR_SMALL

    def get_thumb_img_url(self):
        try:
            return self.img.thumb.url
        except AttributeError:
            return default_avatars.DEFAULT_USER_AVATAR_THUMB

    def get_age(self):
        today = date.today()
        years_difference = today.year - self.birth.year
        is_before_birthday = (today.month, today.day) < (self.birth.month, self.birth.day)
        elapsed_years = years_difference - int(is_before_birthday)
        return elapsed_years

    def get_skiils(self):
        str = self.skill.split(',')
        print(str)
        return list(str)

post_delete.connect(pre_delete_delete_callback, sender=ItUser)
pre_save.connect(pre_save_delete_callback, sender=ItUser)

apps/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import ItUser
from django import forms


class ItUserCreationForm(UserCreationForm):
    birth = forms.CharField(widget=forms.TextInput(attrs={'type': 'date'}), )

    class Meta:
        model = ItUser
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "img",
            "city",
            "birth",
            "specialty",
            "experience",
            "education",
            "about",
            "skills",
            "edu",
            "edu_list",
            "github",
            "bitbacket",
            "pinterest",
            "facebook",
            "instagram",
            "twitter",
            "vk",
        )

api/user/views.py
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework.pagination import PageNumberPagination
from rest_framework import filters
from apps.users.models import ItUser
from .serializers import  ItUserSerializer
from django_filters.rest_framework import DjangoFilterBackend


class ItUserSetPagination(PageNumberPagination):
    page_size = 2
    page_size_query_param = 'page_size'
    max_page_size = 2


class ItUserViewSet(viewsets.ModelViewSet):
    queryset = ItUser.objects.all()
    serializer_class = ItUserSerializer
    pagination_class = ItUserSetPagination
    filter_fields = ('city', 'skills', 'specialty', 'edu')
    search_fields = ('first_name', 'last_name')
    filter_backends = (filters.SearchFilter, DjangoFilterBackend)

apps/users/views.py
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import RedirectView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView

from apps.users.forms import ItUserCreationForm
from settings.base import LOGIN_URL
from .models import ItUser


class ItUserListView(LoginRequiredMixin, ListView):
    model = ItUser


class ItUserDetailView(LoginRequiredMixin, DetailView):
    model = ItUser
    template_name = 'main/home.html'
    context_object_name = 'it_user'


class CreateItUserView(CreateView):
    template_name = 'users/create_user.html'
    form_class = ItUserCreationForm
    success_url = '/'


class LoginView(FormView):
    success_url = '/'
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = 'users/login.html'

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to


class LogoutView(RedirectView):
    url = LOGIN_URL

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

templates/users/create_user.html
{% extends 'base.html' %}

{% block content %}
    <div class="right">
<form action="{% url 'user:registration' %}"
      method="post"
      enctype="multipart/form-data"
      class="pure-form pure-form-stacked"
>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="создать" class="form-control btn-primary">
    </form>
    </div>
{% endblock %}

templates/users/ituser_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Разработчики
{% endblock %}

{% block content %}

    <div class="right">
			<div class="headline">
				<div class="head_title">Разработчики</div>
				<ul class="head_menu">
					<li><a class="active" href="#" title="Все">Все</a></li>
					<li><a href="#" title="Коллеги">Коллеги</a></li>
					<li><a href="#" title="Подписан">Подписан</a></li>
					<li><a href="#" title="Подписки">Подписки</a></li>
				</ul>
				<div class="filter">
					<form>
						<input class="input_text search" type="text" value="">
						<select class="input_select">
							<option>Все</option>
							<option>бекенд-разработчик</option>
							<option>фронтенд-разработчик</option>
							<option>android-разработчик</option>
							<option>ios-разработчик</option>
							<option>дизайнер</option>
							<option>верстальщик</option>
							<option>десктоп-разработчик</option>
						</select>
						<select class="input_select">
							<option>Все города</option>
							<option>Москва</option>
							<option>Санкт-питербур</option>
							<option>Махачкала</option>
							<option>Каспийск</option>
							<option>Дербент</option>
							<option>Кизляр</option>
							<option>Хасавюрт</option>
						</select>
						<div>
						<input id="inputcheckbox" type="checkbox">
						<label for="inputcheckbox">Обучает</label>
						</div>
						<input class="input_text" type="text" placeholder="Навыки">
					</form>
				</div>
				<div class="filter_but"></div>
			</div>
			<div class="list_item">
            {% for ituser in ituser_list %}

				<div class="item_block shadow_box">
				<a class="a_item_block" href="{% url 'user:detail' ituser.id %}" >
					<div class="learner">
                        {% if ituser.edu %}
					    <img src="{% static 'images/learner.png' %}" alt="Ученик">
					    {% endif %}
                    </div>
					<div class="img_item" style="background: url({{ ituser.img.thumb.url }}) center center / cover no-repeat;">
						<img src="{{ ituser.img.thumb.url }}" alt="{{ ituser.username }}" style="opacity: 0;">
					</div>
					<div class="name_item">{{ ituser.first_name }} {{ ituser.last_name }}, {{ ituser.get_age }} лет</div>
					<div class="pos_item">{{ ituser.get_specialty_display }}</div>
					<div class="skills_item">
                    <div class="skills_item">
						<a href="#" class="skill_teg_item">Python</a>
						<a href="#" class="skill_teg_item">JavaScript</a>
						<a href="#" class="skill_teg_item">Angular</a>
						<a href="#" class="skill_teg_item">Django</a>
						<a href="#" class="skill_teg_item">Redis</a>
					</div>
					</div>
				</a>
				</div>
				{% endfor %}
			</div>
		</div>

{% endblock %}

templates/users/login.html
<!DOCTYPE html>
<html>
 <head>
   <title>IT-place</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="/static/css/reset.css" rel="stylesheet" media="screen">
   <link href="/static/css/lightslider.min.css" rel="stylesheet" media="screen">
   <link href="/static/css/styles.css" rel="stylesheet" media="screen">
   <link href="/static/css/mainpage.css" rel="stylesheet" media="screen">
   <link href="/static/css/adaptive.css" rel="stylesheet" media="screen">
 </head>
 <body>
	<div class="main_container">
		<header>
			<div class="adaptive">
			<a class="logo" href="/" title="На главную">IT-place</a>
			<ul>
				<li><a href="#" title="О компании">О компании</a></li>
				<li><a href="#" title="Помощь">Помощь</a></li>
			</ul>
			</div>
		</header>
		<section class="main_block1">
		<div class="adaptive">
		<form class="login" action="{% url 'user:login' %}" method="post">
            {% csrf_token %}
			<input type="text" placeholder="логин" name="username">
			<input type="password" placeholder="пароль" class="pass" name="password">
			<input type="submit" value="Войти">
		</form>
		</div>
		</section>
		<section class="main_block2">
		<div class="adaptive">
			<div class="main_table">
				<div class="main_coll">
				
					<div class="main_title">Разработчикам:</div>
					<div class="main_tegs">web-дизайнеры, backend, frontend, менеджеры</div>
					<div class="main_icon"><img src="/static/images/main1.png" alt="Разработчикам"></div>
					<div class="main_desc">Это площадка, где Вы сможете найти себе команду и проект, быть в курсе событий в IT, сможете найти единомышленников, обучаться у более опытных разработчиков. У Вас будет возможность проверить свой уровень знаний, проходя тесты компаний и других разработчиков. Также, можно будет обучать других платно или бесплатно.</div>
					
				</div>
				<div class="main_coll">
				
					<div class="main_title">Компаниям:</div>
					<div class="main_tegs">менеджеры, IT-компании</div>
					<div class="main_icon"><img src="/static/images/main2.png" alt="Компаниям"></div>
					<div class="main_desc">С помощью IT-place компания сможет пригласить к себе разработчиков , а также проверить их уровень знаний благодаря тестам, просматривать проекты молодых команд, не терять связь с потенциальными сотрудниками. Также, заинтересовать разработчиков с помощью скринкастов, статей и тестов. Компания сможет предложить разработчикам участвовать в своих проектах, тем самым развивая в них необходимые навыки.</div>
					
				</div>
			</div>
		</div>
		</section> 
		<section class="main_block3">
			<div class="regestr adaptive">
			<span><a href="{% url 'user:registration' %}" tilte="Зарегистрироваться как разработчик">Зарегистрироваться как разработчик</a></span>
			<span><a href="#" tilte="Зарегистрироваться как компания">Зарегистрироваться как компания</a></span>
			</div>
		</section>
	</div>
	<script src="/static/js/jquery-3.1.1.min.js"></script>
	<script src="/static/js/lightslider.min.js"></script>
	<script src="/static/js/script.js"></script>
 </body> 
</html>

templates/users/login2.html
{% extends 'base.html' %}

{% block title %}
    Вход
{% endblock %}

{% block content %}
    <form action="{% url 'user:login' %}" method="post" class="pure-form">
        {% csrf_token %}
        <input class="form-control" type="text" name="username" placeholder="Login">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" class="form-control btn-primary">
    </form>
    <p>
        <a href="{% url 'user:registration' %}">registration</a>
    </p>
{% endblock %}

templates/users/update_user.html
{% extends 'base.html' %}

{% block title %}
    Редактирование профиля
{% endblock %}

{% block content %}
<form action="{% url 'user:update' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="form-control btn-primary">
    </form>
{% endblock %}