api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api.user.views import ItUserViewSet


router = routers.DefaultRouter()
router.register(r'user', ItUserViewSet)


urlpatterns = [
    url(r'^', include(router.urls)),
]

apps/events/urls.py
from django.conf.urls import url
from .views import ListEventView, DetailEventView, CreateEventView


urlpatterns = [
    url(r'^$', ListEventView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', DetailEventView.as_view(), name='detail'),
    url(r'^create$', CreateEventView.as_view(), name='create'),
]

base/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from settings import dev as settings

urlpatterns = [
    # contrib
    url(r'^admin/', admin.site.urls),

    # apps
    url(r'^user/', include('apps.users.urls', namespace='user')),
    url(r'^events/', include('apps.events.urls', namespace='event')),
    url(r'^projects/', include('apps.projects.urls', namespace='projects')),

    # rest-api
    url(r'^rest-api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # main
    url(r'^', include('apps.main.urls', namespace='main')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/events/models.py
from django.db import models
from django.db.models.signals import post_delete, pre_save
from django.utils.translation import ugettext_lazy as _
from stdimage.models import StdImageField
from stdimage.utils import pre_delete_delete_callback, pre_save_delete_callback
from stdimage.validators import MaxSizeValidator

from apps.users.models import ItUser
from apps.users.models import Specialty
from settings import default_avatars
from utils.choices import CITIES, EVENT_TYPE


def avatar_path(instance, filename):
    return 'avatars/{0}/{1}/{2}/{3}/{4}'.format(instance.city, instance.type,
                                                instance.title[:1], instance.title[:2], instance.title)


class Event(models.Model):
    title = models.CharField(_('Название'), max_length=100)
    # slug = AutoSlugField(populate_from='title', unique_with='date_start__month')
    type = models.CharField(_('Какое мероприятие'), max_length=100, choices=EVENT_TYPE, default='hak')
    date_start = models.DateTimeField(_('Дата начала'))
    date_end = models.DateTimeField(_('Дата окончания'))
    img = StdImageField(
        _("Аватар"),
        upload_to=avatar_path,
        variations={'thumb': (150, 150, True), 'small': (50, 50, True)},
        validators=[MaxSizeValidator(1028, 768)],
        null=True
    )
    city = models.CharField(_('Город'), max_length=100, choices=CITIES, default='msk')
    specialty = models.ManyToManyField(Specialty, verbose_name=_('Специальность'))
    about = models.TextField(_('Описание'), max_length=2000)
    facebook = models.CharField(max_length=100, blank=True)
    instagram = models.CharField(max_length=100, blank=True)
    twitter = models.CharField(max_length=100, blank=True)
    vk = models.CharField(max_length=100, blank=True)
    create_by = models.ForeignKey(ItUser, verbose_name=_('Создатель'), related_name='my_events')
    members = models.ManyToManyField(ItUser, verbose_name=_('Участники'), blank=True, related_name='events')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Event'
        verbose_name_plural = 'Events'

    def get_small_img_url(self):
        try:
            return self.img.small.url
        except AttributeError:
            return default_avatars.DEFAULT_EVENT_AVATAR_SMALL

    def get_thumb_img_url(self):
        try:
            return self.img.thumb.url
        except AttributeError:
            return default_avatars.DEFAULT_EVENT_AVATAR_THUMB


post_delete.connect(pre_delete_delete_callback, sender=Event)
pre_save.connect(pre_save_delete_callback, sender=Event)

apps/events/forms.py
from django.forms import ModelForm
from django import forms
from .models import Event
from django.contrib.admin import widgets


class EventCreationForm(ModelForm):
    date_start = forms.CharField(widget=forms.TextInput(attrs={'type': 'datetime-local'}),)
    date_end = forms.CharField(widget=forms.TextInput(attrs={'type': 'datetime-local'}),)

    class Meta:
        model = Event
        fields = (
            "title",
            "type",
            "date_start",
            "date_end",
            "img",
            "specialty",
            "city",
            "about",
            "facebook",
            "instagram",
            "twitter",
            "vk",
        )

    # def __init__(self, *args, **kwargs):
    #     super(EventCreationForm, self).__init__(*args, **kwargs)
    #     self.fields['date_start'].widget = widgets.AdminSplitDateTime()
    #     self.fields['date_end'].widget =

apps/events/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse
from .models import Event
from .forms import EventCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin


class ListEventView(LoginRequiredMixin, ListView):
    model = Event

    def get_context_data(self, **kwargs):
        context = super(ListEventView, self).get_context_data(**kwargs)
        # context['now'] = timezone.now()
        return context


class DetailEventView(LoginRequiredMixin, DetailView):
    model = Event

    def get_context_data(self, **kwargs):
        context = super(DetailEventView, self).get_context_data(**kwargs)
        # context['now'] = timezone.now()
        return context


class CreateEventView(CreateView):
    template_name = 'events/create.html'
    form_class = EventCreationForm

    def get_success_url(self):
        return reverse('event:detail', args=(self.object.pk,))

    def form_valid(self, form):
        form.instance.create_by = self.request.user
        return super(CreateEventView, self).form_valid(form)

templates/events/create.html
{% extends 'base.html' %}
{% block title %}
    Новое мероприятие
{% endblock %}
{% block content %}
    <div class="right">
<form action="{% url 'event:create' %}"
      method="post"
      enctype="multipart/form-data"
      class="pure-form pure-form-stacked"
>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="form-control btn-primary" value="Создать мероприятие">
    </form>
    </div>
{% endblock %}

templates/events/event_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="right">
			<div class="left_container">

				<div class="module_photo shadow_box">
					<div class="date_item">
						<span class="numb_item">{{ event.date_start|date:'j' }}-{{ event.date_end|date:'j' }}</span>
						<span class="mount_item">{{ event.date_start|date:'M' }}</span>
					</div>
					<div class="cont_event" style="background: url({{ event.img.thumb.url }}) center center / cover no-repeat;">
						<img src="{{ event.img.thumb.url }}" alt="Фотография">
					</div>
					<div class="line">

					<div class="time_item"><span class="bef_time">{{ event.date_start|date:'G:i'}}
                    </span>-<span class="aft_time">{{ event.date_end|date:'G:i' }}</span></div>

					</div>
				</div>

				<div class="module_subscribes shadow_box">
					<ul>
						<li><a class="subscription" href="#" title="Подписки">Вступить</a></li>
						<li><a class="followers" href="#" title="Подписчики">Участвуют <strong>(39)</strong></a></li>
					</ul>
				</div>

			</div>
			<div class="right_container">
			<div class="profile_info shadow_box">
				<div class="block1 evblock1">
					<div class="lefthead_event">
						<div class="title_event">Название мероприятия</div>
						<div class="type_event">{{ event.get_type_display }}</div>
					</div>
					<div class="righthead_event">
						<img src="/static/images/nophoto.jpg" width="20px" alt="Нет фото">
						<div class="creat_event">Создатель</div>
						<div class="creator_event">{{ event.create_by.first_name }} {{ event.create_by.second_name }}</div>
					</div>
				</div>
				<div class="block2">
					<div class="row">
						<div class="cell">Город:</div>
						<div class="cell">{{ event.get_city_display }}</div>
					</div>
					<div class="row">
						<div class="cell">Для кого:</div>
						<div class="cell">{% for spec in event.specialty.all %} {{ spec }} {% endfor %}</div>
					</div>
					<div class="row">
						<div class="cell">Описание:</div>
						<div class="cell">{{ event.about }}</div>
					</div>
				</div>
			</div>
			<div class="profile_skills">
				<a href="#" class="skill_teg shadow_box">Python</a>
				<a href="#" class="skill_teg shadow_box">JavaScript</a>
				<a href="#" class="skill_teg shadow_box">Angular</a>
				<a href="#" class="skill_teg shadow_box">Django</a>
				<a href="#" class="skill_teg shadow_box">Redis</a>
				<a href="#" class="skill_teg shadow_box">RestApi</a>
				<a href="#" class="skill_teg shadow_box">Php</a>
				<a href="#" class="skill_teg shadow_box">HTML</a>
				<a href="#" class="skill_teg shadow_box">CSS</a>
				<a href="#" class="skill_teg shadow_box">CSS3</a>
			</div>

			<div class="event_photos shadow_box">
				<div class="event_pht_title">Итоги:</div>
				<a href="#" class="event_pht"><img src="{% static 'images/nophoto.jpg' %}" width="310" tilte="Нет фото"></a>
				<a href="#" class="event_pht"><img src="{% static 'images/nophoto.jpg' %}" width="310" tilte="Нет фото"></a>
				<a href="#" class="event_pht"><img src="{% static 'images/nophoto.jpg' %}" width="310" tilte="Нет фото"></a>
				<a href="#" class="event_pht"><img src="{% static 'images/nophoto.jpg' %}" width="310" tilte="Нет фото"></a>
				<a href="#" class="event_pht"><img src="{% static 'images/nophoto.jpg' %}" width="310" tilte="Нет фото"></a>
				<a href="#" class="event_pht"><img src="{% static 'images/nophoto.jpg' %}" width="310" tilte="Нет фото"></a>
				<a href="#" class="event_pht"><img src="{% static 'images/nophoto.jpg' %}" width="310" tilte="Нет фото"></a>
				<a href="#" class="event_pht"><img src="{% static 'images/nophoto.jpg' %}" width="310" tilte="Нет фото"></a>
				<a href="#" class="event_pht"><img src="{% static 'images/nophoto.jpg' %}" width="310" tilte="Нет фото"></a>
				<div class="rasp"></div>
			</div>

			</div>
		</div>

{% endblock %}

templates/events/event_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="right">
			<div class="headline">
				<div class="head_title">Мероприятия</div>
				<ul class="head_menu projects_menu">
					<li><a class="active" href="#" title="Все">Все</a></li>
					<li><a href="#" title="Мои мероприятия">Мои мероприятия</a></li>
					<li><a href="#" title="Участвую">Участвую</a></li>
				</ul>
				<a class="add_project" href="{% url 'event:create' %}" title="Создать мероприятие">Создать</a>
				<div class="filter">
					<form>
						<input class="input_text search" type="text" value="">
						<select class="input_select">
							<option>Вид мероприятия</option>
							<option>хакатон</option>
							<option>конференция</option>
							<option>выставка</option>
							<option>лекция</option>
						</select>
						<select class="input_select">
							<option>Город</option>
							<option>Москва</option>
							<option>Санкт-питербур</option>
							<option>Махачкала</option>
							<option>Каспийск</option>
							<option>Дербент</option>
							<option>Кизляр</option>
							<option>Хасавюрт</option>
						</select>
					</form>
				</div>
				<div class="filter_but"></div>
			</div>
			<div class="list_item project_list">
                {% for event in event_list %}
				<div class="item_block shadow_box">
				<a class="a_item_block" href="{% url 'event:detail' event.id %}" title="Название проекта">
					<div class="date_item">
						<span class="numb_item">{{ event.date_start|date:'j' }}-{{ event.date_end|date:'j' }}</span>
						<span class="mount_item">{{ event.date_start|date:'M' }}-{{ event.date_end|date:'M' }}</span>
					</div>
					<div class="img_item_project" style="background: url({{ event.img.thumb.url }}) center center / cover no-repeat">
						<img src="{{ event.img.thumb.url }}" alt="Название проекта" style="opacity: 0;                          ">
					</div>
					<div class="title_item">{{ event.title }}</div>
					<div class="place_item">{{ event.get_type_display }}<div class="time_item">
                        <span class="bef_time">{{ event.date_start|date:'G:i' }}</span>
                    - <span class="aft_time">{{ event.date_end|date:'G:i' }}</span></div></div>
					<div class="desc_item">Для кого: {% for spec in event.specialty.all %} {{ spec }} {% endfor %}</div>
					<div class="inv_item">Участвуют<strong>(37)</strong></div>
				</a>
				</div>
				 {% endfor %}
			</div>
		</div>
{% endblock %}

templates/events/update.html
{% extends 'base.html' %}

{% block title %}
    Редактирование профиля
{% endblock %}

{% block content %}
<form action="{% url 'event:update' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="form-control btn-primary">
    </form>
{% endblock %}